# Generated by Django 5.2.7 on 2025-11-03 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SISWA', 'Siswa'), ('GURU', 'Guru')], default='SISWA', max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ruangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_ruangan', models.CharField(max_length=200)),
                ('guru_pengajar', models.ManyToManyField(related_name='ruangan_diajar', to=settings.AUTH_USER_MODEL)),
                ('siswa_terdaftar', models.ManyToManyField(blank=True, related_name='ruangan_diikuti', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Materi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('deskripsi', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='materi_files/')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('ruangan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materi_list', to='core.ruangan')),
            ],
        ),
        migrations.CreateModel(
            name='Jadwal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hari', models.CharField(max_length=10)),
                ('jam_mulai', models.TimeField()),
                ('jam_selesai', models.TimeField()),
                ('ruangan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadwal_list', to='core.ruangan')),
            ],
        ),
    ]
