# Generated by Django 5.2.7 on 2025-11-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadwal',
            name='hari',
            field=models.CharField(choices=[('SENIN', 'Senin'), ('SELASA', 'Selasa'), ('RABU', 'Rabu'), ('KAMIS', 'Kamis'), ('JUMAT', 'Jumat'), ('SABTU', 'Sabtu'), ('MINGGU', 'Minggu')], max_length=10),
        ),
    ]
