# Generated by Django 5.2.7 on 2025-11-03 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_jadwal_hari'),
    ]

    operations = [
        migrations.AddField(
            model_name='jadwal',
            name='tanggal',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
