# Generated by Django 5.2.7 on 2025-11-03 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_jadwal_tanggal'),
    ]

    operations = [
        migrations.AddField(
            model_name='jadwal',
            name='judul',
            field=models.CharField(default='Tanpa Judul', max_length=200),
        ),
    ]
